### ISSUE TITLE
FuncTank function not working for player.

### ISSUE THREAD

**Issue by hammermaps** [Admer456/halflife-vs2019-sohl12#8]
I found an error, it is not possible to use the FuncTank function as a player.

Please try it out.

`https://www.youtube.com/watch?v=tlu2MPPR9hw&feature=youtu.be`

**Comment by hammermaps** [comment]
Update:
I tried a version before my changes and found that the problem already existed.
In the original Laurie Cheers SOHL 1.2, the problem does not exist.
So there should have been a problem when porting to the new SDK.

**Comment by Admer456** [comment]
Good catch! I suspect the problem is either in CBasePlayer::PlayerUse or one of CFuncTank methods.
I'll work on it tomorrow, it'll be a pretty simple fix.

**Comment by Admer456** [comment]
I think I might've fixed it. Expect it to be in one of the upcoming commits in the next 30 minutes.

**Comment by Admer456** [comment]
Commit 4fc9288 should fix this issue.

**Comment by hammermaps** [comment]
I can confirm the fix.
